# Generated by Django 4.2 on 2024-01-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentNo', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('phoneNo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('cityTown', models.CharField(max_length=100)),
                ('poBox', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('interestedCategories', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('phoneNo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('cityTown', models.CharField(max_length=100)),
                ('poBox', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursecategory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
