# Generated by Django 4.2 on 2024-02-01 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='phoneNo',
            new_name='mobileNo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='employeeID',
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
