# Generated by Django 4.2 on 2024-02-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_teacher_pobox_remove_teacher_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='poBox',
        ),
    ]
