# Generated by Django 4.2 on 2024-03-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teacher_detail_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phoneNo',
            new_name='mobileNo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='province',
        ),
    ]
