# Generated by Django 4.2 on 2024-03-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_phoneno_student_mobileno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cityTown',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='country',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollmentNo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobileNo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
