# Generated by Django 4.2 on 2024-03-12 06:29

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_studentcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
