# Generated by Django 4.2 on 2024-03-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_courserating_options_studentfavouritecourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfavouritecourse',
            options={'verbose_name_plural': '7. Student Favourite Courses'},
        ),
    ]
