# Generated by Django 4.2 on 2024-03-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_studentfavouritecourse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfavouritecourse',
            options={},
        ),
    ]
