# Generated by Django 4.2 on 2024-03-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_studentfavouritecourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='assignmentStatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
