# Generated by Django 4.2 on 2024-03-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notifText',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifFor',
            field=models.CharField(max_length=200, verbose_name='Notification For'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifReadStatus',
            field=models.BooleanField(default=False, verbose_name='Notification Status'),
        ),
    ]
