# Generated by Django 4.2 on 2024-03-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
