# Generated by Django 4.2 on 2024-03-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifFor', models.CharField(max_length=200, verbose_name='Notification For')),
                ('notifCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('notifReadStatus', models.BooleanField(default=False, verbose_name='Notification Status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '10. Notifications',
            },
        ),
    ]
