# Generated by Django 4.2 on 2024-03-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
