# Generated by Django 4.2 on 2024-03-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_quiz_quizquestions_coursequiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='questions',
            new_name='question',
        ),
    ]
