# Generated by Django 4.2 on 2024-03-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_questions_quizquestions_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseQuiz',
        ),
    ]
