# Generated by Django 4.2 on 2024-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_attemptquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquiz',
            name='rightAnswer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
