# Generated by Django 4.2 on 2024-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_teacherstudentchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebookURL',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagramURL',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitterkURL',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='websiteURL',
            field=models.URLField(null=True),
        ),
    ]
