# Generated by Django 4.2 on 2024-04-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_teacher_facebookurl_teacher_instagramurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='twitterkURL',
            new_name='twitterURL',
        ),
    ]
