# Generated by Django 4.2 on 2024-05-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_useraccount'),
    ]

    operations = [
    ]
