# Generated by Django 4.2 on 2024-05-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20240512_1322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='auth_user',
        ),
    ]
