# Generated by Django 4.2 on 2024-05-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_useraccount_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
