# Generated by Django 4.2 on 2024-05-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
