# Generated by Django 4.2 on 2024-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
