# Generated by Django 4.2 on 2024-06-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
