# Generated by Django 4.2 on 2024-06-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teacher_detail_alter_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobileNo',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
