# Generated by Django 4.2 on 2024-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_submitted_at_studentexam_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='answer_text',
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='studentexam',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
    ]
