# Generated by Django 4.2 on 2024-07-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_text_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_taken', to='main.student'),
        ),
    ]
